### ISSUE TITLE
FASE 3

### ISSUE THREAD

**Issue by juliandariomirandacalle** [CiroGamboa/EdenServer#11]
##### OBJETIVO ESPECÍFICO 3
- [ ] Actividad 3.1. - Implementación del modelo de interacción de los componentes del sistema distribuido.
- [ ] Actividad 3.2. - Implementación de los protocolos básicos de aseguramiento al servidor del sistema distribuido.
- [ ] Actividad 3.3. - Integración de los modelos de interacción de componentes  y aseguramiento del sistema: Middleware.
