### ISSUE TITLE
Actividad 2.2 - Desarrollo de las bases de datos y el middleware inicial

### ISSUE THREAD

**Issue by juliandariomirandacalle** [CiroGamboa/EdenServer#14]
Esta actividad tendrá en cuenta el desarrollo de la base de datos en:

- [ ] Servidor Principal de Edén
- [ ] Servidor de Lagajari
- [ ] Servidor de Humus
- [ ] Servidor de Leroy Merlín
- [ ] Servidor de Librería Nacional

Por otro lado, se poblará las bases de datos concernientes con:

- [ ] Servidor Principal de Edén
- [ ] Servidor de Lagajari
- [ ] Servidor de Humus
- [ ] Servidor de Leroy Merlín
- [ ] Servidor de Librería Nacional
