### ISSUE TITLE
Codificación Distribuidores

### ISSUE THREAD

**Issue by juliandariomirandacalle** [CiroGamboa/EdenServer#3]
- [ ] Orgánicos Lagajari - Semillas
 - [ ] Humus - Abono
 - [ ] Leroy Merlí- Herramientas
 - [ ] Librería Nacional Agrícola de Bogotá - Libros
