### ISSUE TITLE
Actividad 3.1 - Implementación del modelo de interacción

### ISSUE THREAD

**Issue by juliandariomirandacalle** [CiroGamboa/EdenServer#35]
Implementación del modelo de interacción en:

- [ ] Servidor Principal de Edén
- [ ] Servidor de Lagajari
- [ ] Servidor de Humus
- [ ] Servidor de Leroy Merlín
- [ ] Servidor de LNAB
